fixtures:
  repositories:
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    lvm: git://github.com/puppetlabs/puppetlabs-lvm.git
  symlinks:
    apt: "#{source_dir}"
    lvm: "#{source_dir}"
