fixtures:
  repositories:
    apt: git://github.com/puppetlabs/puppetlabs-apt.git
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    lvm: git://github.com/puppetlabs/puppetlabs-lvm.git
    tfenv: git://github.com/SergK/puppet-tfenv
    vcsrepo: git://github.com/puppetlabs/puppetlabs-vcsrepo
    rvm: git://github.com/maestrodev/puppet-rvm
    gnupg: git://github.com/dgolja/golja-gnupg
    staging: git://github.com/voxpupuli/puppet-staging
  symlinks:
    apt: "#{source_dir}"
    lvm: "#{source_dir}"
    tfenv: "#{source_dir}"
    vcsrepo: "#{source_dir}"
    staging: "#{source_dir}"
